baseURL = 'https://neontemple.net/'
languageCode = 'en-us'
title = 'Neon Temple'
theme = 'terminal'

[params]
  description = 'A cybersecurity guild in Tampa Bay. Not a cult!'
  coterieAPI = 'https://coterie.stage.grc.red'
  portalURL = 'https://coterie.stage.grc.red/login'

  # Social links
  email = 'info@neontemple.net'
  facebook = ''
  twitter = ''
  youtube = ''
  instagram = ''

  # Address
  address = ''

[menus]
  [[menus.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menus.main]]
    name = 'Calendar'
    url = '/calendar/'
    weight = 2
  [[menus.main]]
    name = 'Announcements'
    url = '/announcements/'
    weight = 3
  [[menus.main]]
    name = 'About'
    url = '/about/'
    weight = 4
  [[menus.main]]
    name = 'Join'
    url = '/join/'
    weight = 5
  [[menus.main]]
    name = 'Swag'
    url = 'https://www.ransomwear.store/collections/vault/Vault+vault'
    weight = 6
    [menus.main.params]
      external = true
  [[menus.main]]
    name = 'Login'
    url = 'https://coterie.stage.grc.red/login'
    weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
